name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: List Directory
      run: ls -lh **/*
    - name: List Directory
      run: ls -lh tv/build/outputs
    - name: List Directory
      run: ls -lh tv/build/generated
    - name: List APKs
      run: find . -type f -regex ".*\.apk" -ls
    - name: Sign Release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: tv/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    - name: Get TV Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TV Build Artifact
        path: tv/build/outputs/apk/release/*.apk
    - name: Get Mobile Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mobile Build Artifact
        path: mobile/build/outputs/apk/release/*.apk
